// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-about.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
var ABOUT = {
  name: "Tenzing Jampa",
  headline: "Engineering Physics graduate from IIT Bombay; incoming Master's student in Physics at KIT",
  hometown: "Kalimpong, Eastern Himalayas",
  location: "Mumbai, India",
  bio: [
    "I'm Tenzing, an Engineering Physics graduate from IIT Bombay, originally from Kalimpong in the eastern Himalayas. I will begin a Master's degree in Physics at Karlsruhe Institute of Technology (KIT) in the Winter 2026/27 semester. My work tends to sit at the intersection of physics and computation \u2014 modelling polymer chains, simulating wind turbine drive trains, or training RL agents.",
    "I spent Autumn 2025 as an exchange student at the University of Agder in Norway, which was equal parts great research experience and a genuine culture shock. Outside academics, I play basketball, speak six languages, and pick up random side projects that usually teach me more than I expected."
  ],
  quickFacts: [
    "Engineering Physics graduate \xB7 IIT Bombay ('26)",
    "Incoming Master's student in Physics \xB7 KIT \xB7 Winter 2026/27",
    "Condensed Matter \xB7 Nonlinear Dynamics \xB7 Astrophysics",
    "Top 1.1% JEE Main \xB7 Top 2.6% JEE Advanced",
    "Six languages: English, Hindi, Nepali, Tibetan, Japanese, German",
    "Exchange Student \xB7 University of Agder, Norway ('25)",
    "Basketball \xB7 3rd place, IIT Bombay General Championships ('25)",
    "Based in Mumbai, India"
  ],
  skills: [
    "Python",
    "C++",
    "MATLAB / Simulink",
    "Machine Learning",
    "LaTeX",
    "Scikit-learn",
    "PyTorch",
    "Nonlinear Dynamics",
    "Figma",
    "Knime"
  ]
};
var get_about_default = defineTool({
  name: "get_about",
  title: "Get about Tenzing",
  description: "Returns Tenzing Jampa's bio, quick facts, and skills from the portfolio's About section.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(ABOUT, null, 2) }],
    structuredContent: ABOUT
  })
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
var PROJECTS = [
  {
    title: "Wind Turbine Drive Train Simulation",
    tag: "Research \xB7 University of Agder, Norway",
    description: "High-fidelity MATLAB/Simulink model of a 2MW wind turbine drive train with a five-interval control strategy regulating rotor speed across 0\u201325 m/s. Models generator torque and hydraulic pitch servo dynamics; verified via transient ramp and step-jump simulations.",
    technologies: ["MATLAB", "Simulink", "Simscape", "Control Systems"],
    link: "https://github.com/VanTenny/Wind_Turbine_Project_Researcher",
    category: "featured"
  },
  {
    title: "Statistical Mechanics of Polymer Chains",
    tag: "B.Tech Project \xB7 IIT Bombay",
    description: "Derived scaling laws for freely jointed, freely rotating, and worm-like chain architectures. Applied Flory mean-field theory and the thermal blob model to map ideal Gaussian to swollen coil states; simulations confirmed the R ~ N^(3/5) exponent for self-avoiding walks.",
    technologies: ["Statistical Physics", "Python", "Monte Carlo", "Scaling Theory"],
    link: "https://github.com/VanTenny/BTP_Project_Tenzing/blob/main/22B1808_Report.pdf",
    category: "featured"
  },
  {
    title: "Mechanical Impacting System \u2014 Electrical Analogue",
    tag: "Non-linear Dynamics \xB7 IIT Bombay",
    description: "Reproduced and extended a published paper on the electrical equivalent of a 1-DOF mechanical impacting system. Identified conditions for the period-1 \u2192 chaos \u2192 period-2 bifurcation and resolved a flaw in the original analysis using Python phase plots and differential calculus.",
    technologies: ["Python", "LTspice", "Nonlinear Dynamics", "Bifurcation Analysis"],
    link: "https://github.com/VanTenny/Mechanical-Impacting-Simulation-System/blob/main/Mechanical%20Impacting%20Systems-compressed.pdf",
    category: "featured"
  },
  {
    title: "RL Agent for Highway Self-Driving",
    tag: "Machine Learning \xB7 IIT Bombay Summer of Coding",
    description: "Implemented and compared Q-Learning, PPO, DDPG, and SAC on a simulated highway environment across an 8-week structured programme.",
    technologies: ["Python", "PyTorch", "PPO", "DDPG", "SAC", "OpenAI Gym"],
    link: "https://github.com/VanTenny/Reinforcement-Learning-in-Self-Driving-Cars",
    category: "featured"
  },
  {
    title: "Cosmology and Dark Matter \u2014 Research Report",
    tag: "Self Project \xB7 IIT Bombay Summer of Science",
    description: "8-week dive into foundational and frontier cosmology: Big Bang, CMB, GR in cosmological models, and dark matter candidates (WIMPs, axions, sterile neutrinos). Written in LaTeX with figures and derivations.",
    technologies: ["Astrophysics", "General Relativity", "LaTeX", "Scientific Writing"],
    link: "https://github.com/VanTenny/cosmology-and-dark-matter-report/blob/main/SOS_Tenzing.pdf",
    category: "featured"
  },
  {
    title: "Universal IR Remote Controller",
    tag: "Electronics \xB7 IIT Bombay",
    description: "Microcontroller-based universal IR remote that decodes and replays signals from common consumer electronics \u2014 a first-year intro to embedded signal handling.",
    technologies: ["Arduino", "C", "IR Protocols", "Embedded"],
    link: "https://thiv.notion.site/Universal-IR-Remote-29823ba45c8b4f3eb3f5b599a5765c0f",
    category: "smaller"
  },
  {
    title: "Line Following Bot",
    tag: "Robotics \xB7 IIT Bombay",
    description: "Two-wheeled line follower with IR reflectance sensors and a PID-tuned motor loop. Selected as one of the best out of 120+ teams for the institute-wide exhibition.",
    technologies: ["Arduino", "PID Control", "IR Sensors", "Circuit Design"],
    link: "https://youtu.be/mOh8zv66rmA",
    category: "smaller"
  }
];
var list_projects_default = defineTool2({
  name: "list_projects",
  title: "List projects",
  description: "Lists Tenzing's portfolio projects (featured and smaller). Optionally filter by category.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(PROJECTS, null, 2) }],
    structuredContent: { projects: PROJECTS }
  })
});

// src/lib/mcp/tools/list-achievements.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
var ACHIEVEMENTS = [
  { title: "TOEFL iBT \u2014 99/120 (CEFR C1)", year: "2025", description: "99/120 on the TOEFL iBT with a perfect 30/30 in Listening (Reading 24, Listening 30, Speaking 20, Writing 25). CEFR C1 \u2014 Advanced English proficiency." },
  { title: "Top 1.10% in JEE Main", year: "2022", description: "Top 1.10% among 0.9 million+ candidates in JEE Main." },
  { title: "Top 2.57% in JEE Advanced", year: "2022", description: "Top 2.57% rank among 0.15 million+ candidates in JEE Advanced." },
  { title: "Institute Exhibition Selection", year: "2023", description: "One of the best teams out of 120+ selected for the institute-wide exhibition for the Line Following Bot project at IIT Bombay." },
  { title: "Perfect Score in Product Design", year: "2025", description: "Perfect score (10/10) from PhD-level evaluators for all product design projects in the DE344 course." },
  { title: "A+ in Japanese Communication", year: "2024", description: "A+ in a 100-hour Japanese Communication course by IIT Bombay's Office of International Relations." },
  { title: "Basketball Championship Podium", year: "2025", description: "3rd place in the Hostel 5 General Championships at IIT Bombay after a yearlong basketball training." },
  { title: "Mount Fuji Summit", year: "2025", description: "Climbed Mount Fuji in Japan on a challenging seven-hour ascent to the summit." }
];
var list_achievements_default = defineTool3({
  name: "list_achievements",
  title: "List achievements",
  description: "Lists Tenzing's achievements and recognitions from the portfolio.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(ACHIEVEMENTS, null, 2) }],
    structuredContent: { achievements: ACHIEVEMENTS }
  })
});

// src/lib/mcp/tools/list-coursework.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
var COURSEWORK = [
  { category: "Mathematics", courses: ["Calculus", "Linear Algebra", "Differential Equations", "Real Analysis", "Complex Analysis"] },
  { category: "Systems & Control", courses: ["Non-linear Dynamics", "Digital Photogrammetry and Cartography"] },
  { category: "Physics", courses: ["Classical Mechanics", "Quantum Mechanics", "Statistical Physics", "Numerical Methods in Physics", "Mathematical Physics", "Waves and Oscillations", "Quantum Information and Computing", "Semiconductors Physics", "Condensed Matter Physics", "Electromagnetic Theory", "Light Matter Interaction", "Molecular Spectroscopy", "Optical Physics", "Continuum Mechanics"] },
  { category: "Electrical", courses: ["Analog Electronics", "Digital Electronics", "Microprocessors", "Nano Devices and Applications"] },
  { category: "CS and ML", courses: ["Computer Programming and Utilisation", "Programming for Data Science", "Makers Space", "Introduction to Machine Learning"] }
];
var list_coursework_default = defineTool4({
  name: "list_coursework",
  title: "List coursework",
  description: "Lists Tenzing's selected coursework at IIT Bombay, grouped by category.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(COURSEWORK, null, 2) }],
    structuredContent: { coursework: COURSEWORK }
  })
});

// src/lib/mcp/tools/list-gallery.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
var GALLERY = [
  { title: "Basketball Championship", description: "Secured 3rd place in Hostel 5 General Championships at IIT Bombay" },
  { title: "Marathon Achievement", description: "Participating in my first 5K Run organized by Avhaan IITB" },
  { title: "Hiking", description: "At the summit of Rajgad fort, Maharashtra with my friends" },
  { title: "EP_26", description: "Graduation Photoshoot of Engineering Physics batch '26" },
  { title: "Milan", description: "At Duomo di Milano, Italy" },
  { title: "Norway", description: "Homecooked dinner by me, Nanako and Asumi for our international friends at UiA, Kristiansand" },
  { title: "Oslo", description: "The upper deck of Astrup Fearnley Museum of Modern Art in Oslo, Norway" },
  { title: "Paris", description: "At a museum in Paris, France" },
  { title: "Preikestolen (Pulpit Rock)", description: "Summited a world famous nature's wonder Preikestolen, Norway" },
  { title: "Mount Fuji", description: "Climbed Mount Fuji on a crazy hike which took around 7 hours" },
  { title: "Osaka Palace", description: "Travelling and being crazy about Japan define me" },
  { title: "Cultural Exchange Dinner", description: "Enjoying time with friends from various countries" }
];
var list_gallery_default = defineTool5({
  name: "list_gallery",
  title: "List gallery photos",
  description: "Lists photos in Tenzing's portfolio gallery with their titles and captions.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(GALLERY, null, 2) }],
    structuredContent: { photos: GALLERY }
  })
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
var CONTACT = {
  officialEmail: "22B1808@iitb.ac.in",
  personalEmail: "jampatenzin280@gmail.com",
  phone: "+918016037894",
  github: "https://github.com/VanTenny",
  linkedin: "https://linkedin.com/in/TenzinZen27",
  cv: "https://github.com/VanTenny/CV/blob/main/CV_Tenzing.pdf"
};
var get_contact_default = defineTool6({
  name: "get_contact",
  title: "Get contact info",
  description: "Returns Tenzing's public contact information and links (email, phone, GitHub, LinkedIn, CV).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(CONTACT, null, 2) }],
    structuredContent: CONTACT
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "tenzing-portfolio-mcp",
  title: "Tenzing Jampa \u2014 Portfolio MCP",
  version: "0.1.0",
  instructions: "Read-only access to Tenzing Jampa's public portfolio: bio, projects, achievements, coursework, gallery captions, and contact links. Use get_about for a general overview, then drill into list_projects, list_achievements, list_coursework, list_gallery, or get_contact as needed.",
  tools: [get_about_default, list_projects_default, list_achievements_default, list_coursework_default, list_gallery_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
